apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hpc-custom
  region: us-west-2
iam:
  withOIDC: true
availabilityZones: ["us-west-2a", "us-west-2b"]
vpc:
  id: vpc-07b388829583e6dc7
  subnets:
    private:
      us-west-2a: { id: subnet-0bdd69129d90bf460 }
      us-west-2b: { id: subnet-0bb4f4ad200d15838 }
  securityGroup: sg-0b909b1be3ae459a7
managedNodeGroups:
  - name: override
    iam:
      instanceRoleARN: arn:aws:iam::376129860391:role/EKSCustomClusterNodeRole
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels:
      cpu-manager: "enabled"
      nodegroup-type: "override"
    tags:
      nodegroup-type: "override"
    privateNetworking: true
    efaEnabled: true
    availabilityZones: ["us-west-2a"]
#    subnets:
#      - subnet-0bdd69129d90bf460
#      - subnet-0bb4f4ad200d15838
    launchTemplate:
      id: lt-03c9ef1f7c3ff2fd2
      version: "31"
